### ISSUE TITLE
首页仍然提示需要下载melonloader

### ISSUE THREAD

**Issue by cothurn** [LocalizeLimbusCompany/LLC_Wiki#11]
如图：
![image](https://github.com/LocalizeLimbusCompany/LLC_Wiki/assets/14202194/4112b460-dd25-4ed5-a02c-cf0760a58cf3)
解决方式：
把它删了

**Comment by N071** [comment]
了解，感谢捉虫❤

**Comment by N071** [comment]
[Commit 8721f70](https://github.com/LocalizeLimbusCompany/LLC_Wiki/commit/8721f706c03c8f0e49be1eaea799cf2651cfd8a6) 此问题已修复。
