### ISSUE TITLE
Bug: 在手机端浏览LLC_Wiki时，下载按钮样式混乱

### ISSUE THREAD

**Issue by Dr-ZHUIM** [LocalizeLimbusCompany/LLC_Wiki#9]
## 图片描述：

![image](https://github.com/LocalizeLimbusCompany/LLC_Wiki/assets/56201181/e963d0f6-65ab-4c25-8786-2fdfe964f0c4)

## 解决方案：

提供了mdx组件解决样式问题。
PR链接：https://github.com/LocalizeLimbusCompany/LLC_Wiki/pull/8

**Comment by ZengXiaoPi** [comment]
确认无误，已合并。
